name: CI
on:
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Print current working directory
        run: |
          pwd
          ls -lah .

      - name: Install dependencies
        run: npm install

      - name: Run Unit Test
        run: API_KEY=env.API_KEY npm run test

      - name: Run e2e Test
        run: npm run test:e2e
